#!/bin/bash
# coding=utf-8

virtualenv -p python3 proto_env
# shellcheck disable=SC1091
source proto_env/bin/activate
pip install grpcio-tools==1.24.3

function cleanup() {
    # shellcheck disable=SC1091
    rm -rf proto_env
}
trap cleanup EXIT

echo "Generating tts Python protobuf/grpc sources."
path_i="../proto"
path_o="."
python3 -m grpc_tools.protoc \
	        -I${path_i} \
            --python_out=${path_o} \
            --grpc_python_out=${path_o} \
            ${path_i}/techmo_tts.proto

# Fix buggy autogenerated GRPC import
#sed -i 's/import techmo_tts_pb2 as techmo__tts__pb2/from . import techmo_tts_pb2 as techmo__tts__pb2/' ${path_o}/techmo_tts_pb2_grpc.py
