// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tribune_tts.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_tribune_5ftts_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_tribune_5ftts_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3008000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3008000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_tribune_5ftts_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_tribune_5ftts_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[5]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_tribune_5ftts_2eproto;
namespace techmo {
namespace tribune {
class AudioData;
class AudioDataDefaultTypeInternal;
extern AudioDataDefaultTypeInternal _AudioData_default_instance_;
class Error;
class ErrorDefaultTypeInternal;
extern ErrorDefaultTypeInternal _Error_default_instance_;
class SynthesizeConfig;
class SynthesizeConfigDefaultTypeInternal;
extern SynthesizeConfigDefaultTypeInternal _SynthesizeConfig_default_instance_;
class SynthesizeRequest;
class SynthesizeRequestDefaultTypeInternal;
extern SynthesizeRequestDefaultTypeInternal _SynthesizeRequest_default_instance_;
class SynthesizeResponse;
class SynthesizeResponseDefaultTypeInternal;
extern SynthesizeResponseDefaultTypeInternal _SynthesizeResponse_default_instance_;
}  // namespace tribune
}  // namespace techmo
PROTOBUF_NAMESPACE_OPEN
template<> ::techmo::tribune::AudioData* Arena::CreateMaybeMessage<::techmo::tribune::AudioData>(Arena*);
template<> ::techmo::tribune::Error* Arena::CreateMaybeMessage<::techmo::tribune::Error>(Arena*);
template<> ::techmo::tribune::SynthesizeConfig* Arena::CreateMaybeMessage<::techmo::tribune::SynthesizeConfig>(Arena*);
template<> ::techmo::tribune::SynthesizeRequest* Arena::CreateMaybeMessage<::techmo::tribune::SynthesizeRequest>(Arena*);
template<> ::techmo::tribune::SynthesizeResponse* Arena::CreateMaybeMessage<::techmo::tribune::SynthesizeResponse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace techmo {
namespace tribune {

enum ErrorCode : int {
  UNKNOWN = 0,
  LICENCE = 1,
  TEXT_NORMALIZATION = 2,
  TRANSCRIPTION = 3,
  SYNTHESIS = 4,
  ErrorCode_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  ErrorCode_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool ErrorCode_IsValid(int value);
constexpr ErrorCode ErrorCode_MIN = UNKNOWN;
constexpr ErrorCode ErrorCode_MAX = SYNTHESIS;
constexpr int ErrorCode_ARRAYSIZE = ErrorCode_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ErrorCode_descriptor();
template<typename T>
inline const std::string& ErrorCode_Name(T enum_t_value) {
  static_assert(::std::is_same<T, ErrorCode>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function ErrorCode_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    ErrorCode_descriptor(), enum_t_value);
}
inline bool ErrorCode_Parse(
    const std::string& name, ErrorCode* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<ErrorCode>(
    ErrorCode_descriptor(), name, value);
}
// ===================================================================

class SynthesizeRequest :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:techmo.tribune.SynthesizeRequest) */ {
 public:
  SynthesizeRequest();
  virtual ~SynthesizeRequest();

  SynthesizeRequest(const SynthesizeRequest& from);
  SynthesizeRequest(SynthesizeRequest&& from) noexcept
    : SynthesizeRequest() {
    *this = ::std::move(from);
  }

  inline SynthesizeRequest& operator=(const SynthesizeRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline SynthesizeRequest& operator=(SynthesizeRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const SynthesizeRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SynthesizeRequest* internal_default_instance() {
    return reinterpret_cast<const SynthesizeRequest*>(
               &_SynthesizeRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(SynthesizeRequest* other);
  friend void swap(SynthesizeRequest& a, SynthesizeRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline SynthesizeRequest* New() const final {
    return CreateMaybeMessage<SynthesizeRequest>(nullptr);
  }

  SynthesizeRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<SynthesizeRequest>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const SynthesizeRequest& from);
  void MergeFrom(const SynthesizeRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SynthesizeRequest* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "techmo.tribune.SynthesizeRequest";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_tribune_5ftts_2eproto);
    return ::descriptor_table_tribune_5ftts_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string text = 1;
  void clear_text();
  static const int kTextFieldNumber = 1;
  const std::string& text() const;
  void set_text(const std::string& value);
  void set_text(std::string&& value);
  void set_text(const char* value);
  void set_text(const char* value, size_t size);
  std::string* mutable_text();
  std::string* release_text();
  void set_allocated_text(std::string* text);

  // .techmo.tribune.SynthesizeConfig config = 2;
  bool has_config() const;
  void clear_config();
  static const int kConfigFieldNumber = 2;
  const ::techmo::tribune::SynthesizeConfig& config() const;
  ::techmo::tribune::SynthesizeConfig* release_config();
  ::techmo::tribune::SynthesizeConfig* mutable_config();
  void set_allocated_config(::techmo::tribune::SynthesizeConfig* config);

  // @@protoc_insertion_point(class_scope:techmo.tribune.SynthesizeRequest)
 private:
  class HasBitSetters;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr text_;
  ::techmo::tribune::SynthesizeConfig* config_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_tribune_5ftts_2eproto;
};
// -------------------------------------------------------------------

class SynthesizeConfig :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:techmo.tribune.SynthesizeConfig) */ {
 public:
  SynthesizeConfig();
  virtual ~SynthesizeConfig();

  SynthesizeConfig(const SynthesizeConfig& from);
  SynthesizeConfig(SynthesizeConfig&& from) noexcept
    : SynthesizeConfig() {
    *this = ::std::move(from);
  }

  inline SynthesizeConfig& operator=(const SynthesizeConfig& from) {
    CopyFrom(from);
    return *this;
  }
  inline SynthesizeConfig& operator=(SynthesizeConfig&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const SynthesizeConfig& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SynthesizeConfig* internal_default_instance() {
    return reinterpret_cast<const SynthesizeConfig*>(
               &_SynthesizeConfig_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(SynthesizeConfig* other);
  friend void swap(SynthesizeConfig& a, SynthesizeConfig& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline SynthesizeConfig* New() const final {
    return CreateMaybeMessage<SynthesizeConfig>(nullptr);
  }

  SynthesizeConfig* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<SynthesizeConfig>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const SynthesizeConfig& from);
  void MergeFrom(const SynthesizeConfig& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SynthesizeConfig* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "techmo.tribune.SynthesizeConfig";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_tribune_5ftts_2eproto);
    return ::descriptor_table_tribune_5ftts_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 sample_rate_hertz = 1;
  void clear_sample_rate_hertz();
  static const int kSampleRateHertzFieldNumber = 1;
  ::PROTOBUF_NAMESPACE_ID::int32 sample_rate_hertz() const;
  void set_sample_rate_hertz(::PROTOBUF_NAMESPACE_ID::int32 value);

  // @@protoc_insertion_point(class_scope:techmo.tribune.SynthesizeConfig)
 private:
  class HasBitSetters;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::int32 sample_rate_hertz_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_tribune_5ftts_2eproto;
};
// -------------------------------------------------------------------

class SynthesizeResponse :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:techmo.tribune.SynthesizeResponse) */ {
 public:
  SynthesizeResponse();
  virtual ~SynthesizeResponse();

  SynthesizeResponse(const SynthesizeResponse& from);
  SynthesizeResponse(SynthesizeResponse&& from) noexcept
    : SynthesizeResponse() {
    *this = ::std::move(from);
  }

  inline SynthesizeResponse& operator=(const SynthesizeResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline SynthesizeResponse& operator=(SynthesizeResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const SynthesizeResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SynthesizeResponse* internal_default_instance() {
    return reinterpret_cast<const SynthesizeResponse*>(
               &_SynthesizeResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(SynthesizeResponse* other);
  friend void swap(SynthesizeResponse& a, SynthesizeResponse& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline SynthesizeResponse* New() const final {
    return CreateMaybeMessage<SynthesizeResponse>(nullptr);
  }

  SynthesizeResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<SynthesizeResponse>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const SynthesizeResponse& from);
  void MergeFrom(const SynthesizeResponse& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SynthesizeResponse* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "techmo.tribune.SynthesizeResponse";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_tribune_5ftts_2eproto);
    return ::descriptor_table_tribune_5ftts_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .techmo.tribune.AudioData audio = 1;
  bool has_audio() const;
  void clear_audio();
  static const int kAudioFieldNumber = 1;
  const ::techmo::tribune::AudioData& audio() const;
  ::techmo::tribune::AudioData* release_audio();
  ::techmo::tribune::AudioData* mutable_audio();
  void set_allocated_audio(::techmo::tribune::AudioData* audio);

  // .techmo.tribune.Error error = 2;
  bool has_error() const;
  void clear_error();
  static const int kErrorFieldNumber = 2;
  const ::techmo::tribune::Error& error() const;
  ::techmo::tribune::Error* release_error();
  ::techmo::tribune::Error* mutable_error();
  void set_allocated_error(::techmo::tribune::Error* error);

  // @@protoc_insertion_point(class_scope:techmo.tribune.SynthesizeResponse)
 private:
  class HasBitSetters;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::techmo::tribune::AudioData* audio_;
  ::techmo::tribune::Error* error_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_tribune_5ftts_2eproto;
};
// -------------------------------------------------------------------

class AudioData :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:techmo.tribune.AudioData) */ {
 public:
  AudioData();
  virtual ~AudioData();

  AudioData(const AudioData& from);
  AudioData(AudioData&& from) noexcept
    : AudioData() {
    *this = ::std::move(from);
  }

  inline AudioData& operator=(const AudioData& from) {
    CopyFrom(from);
    return *this;
  }
  inline AudioData& operator=(AudioData&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const AudioData& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const AudioData* internal_default_instance() {
    return reinterpret_cast<const AudioData*>(
               &_AudioData_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  void Swap(AudioData* other);
  friend void swap(AudioData& a, AudioData& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline AudioData* New() const final {
    return CreateMaybeMessage<AudioData>(nullptr);
  }

  AudioData* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<AudioData>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const AudioData& from);
  void MergeFrom(const AudioData& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AudioData* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "techmo.tribune.AudioData";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_tribune_5ftts_2eproto);
    return ::descriptor_table_tribune_5ftts_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // bytes content = 2;
  void clear_content();
  static const int kContentFieldNumber = 2;
  const std::string& content() const;
  void set_content(const std::string& value);
  void set_content(std::string&& value);
  void set_content(const char* value);
  void set_content(const void* value, size_t size);
  std::string* mutable_content();
  std::string* release_content();
  void set_allocated_content(std::string* content);

  // int32 sample_rate_hertz = 1;
  void clear_sample_rate_hertz();
  static const int kSampleRateHertzFieldNumber = 1;
  ::PROTOBUF_NAMESPACE_ID::int32 sample_rate_hertz() const;
  void set_sample_rate_hertz(::PROTOBUF_NAMESPACE_ID::int32 value);

  // bool end_of_stream = 3;
  void clear_end_of_stream();
  static const int kEndOfStreamFieldNumber = 3;
  bool end_of_stream() const;
  void set_end_of_stream(bool value);

  // @@protoc_insertion_point(class_scope:techmo.tribune.AudioData)
 private:
  class HasBitSetters;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr content_;
  ::PROTOBUF_NAMESPACE_ID::int32 sample_rate_hertz_;
  bool end_of_stream_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_tribune_5ftts_2eproto;
};
// -------------------------------------------------------------------

class Error :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:techmo.tribune.Error) */ {
 public:
  Error();
  virtual ~Error();

  Error(const Error& from);
  Error(Error&& from) noexcept
    : Error() {
    *this = ::std::move(from);
  }

  inline Error& operator=(const Error& from) {
    CopyFrom(from);
    return *this;
  }
  inline Error& operator=(Error&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Error& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Error* internal_default_instance() {
    return reinterpret_cast<const Error*>(
               &_Error_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  void Swap(Error* other);
  friend void swap(Error& a, Error& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Error* New() const final {
    return CreateMaybeMessage<Error>(nullptr);
  }

  Error* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Error>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Error& from);
  void MergeFrom(const Error& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Error* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "techmo.tribune.Error";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_tribune_5ftts_2eproto);
    return ::descriptor_table_tribune_5ftts_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string description = 2;
  void clear_description();
  static const int kDescriptionFieldNumber = 2;
  const std::string& description() const;
  void set_description(const std::string& value);
  void set_description(std::string&& value);
  void set_description(const char* value);
  void set_description(const char* value, size_t size);
  std::string* mutable_description();
  std::string* release_description();
  void set_allocated_description(std::string* description);

  // .techmo.tribune.ErrorCode code = 1;
  void clear_code();
  static const int kCodeFieldNumber = 1;
  ::techmo::tribune::ErrorCode code() const;
  void set_code(::techmo::tribune::ErrorCode value);

  // @@protoc_insertion_point(class_scope:techmo.tribune.Error)
 private:
  class HasBitSetters;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr description_;
  int code_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_tribune_5ftts_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// SynthesizeRequest

// string text = 1;
inline void SynthesizeRequest::clear_text() {
  text_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& SynthesizeRequest::text() const {
  // @@protoc_insertion_point(field_get:techmo.tribune.SynthesizeRequest.text)
  return text_.GetNoArena();
}
inline void SynthesizeRequest::set_text(const std::string& value) {
  
  text_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:techmo.tribune.SynthesizeRequest.text)
}
inline void SynthesizeRequest::set_text(std::string&& value) {
  
  text_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:techmo.tribune.SynthesizeRequest.text)
}
inline void SynthesizeRequest::set_text(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  text_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:techmo.tribune.SynthesizeRequest.text)
}
inline void SynthesizeRequest::set_text(const char* value, size_t size) {
  
  text_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:techmo.tribune.SynthesizeRequest.text)
}
inline std::string* SynthesizeRequest::mutable_text() {
  
  // @@protoc_insertion_point(field_mutable:techmo.tribune.SynthesizeRequest.text)
  return text_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* SynthesizeRequest::release_text() {
  // @@protoc_insertion_point(field_release:techmo.tribune.SynthesizeRequest.text)
  
  return text_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void SynthesizeRequest::set_allocated_text(std::string* text) {
  if (text != nullptr) {
    
  } else {
    
  }
  text_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), text);
  // @@protoc_insertion_point(field_set_allocated:techmo.tribune.SynthesizeRequest.text)
}

// .techmo.tribune.SynthesizeConfig config = 2;
inline bool SynthesizeRequest::has_config() const {
  return this != internal_default_instance() && config_ != nullptr;
}
inline void SynthesizeRequest::clear_config() {
  if (GetArenaNoVirtual() == nullptr && config_ != nullptr) {
    delete config_;
  }
  config_ = nullptr;
}
inline const ::techmo::tribune::SynthesizeConfig& SynthesizeRequest::config() const {
  const ::techmo::tribune::SynthesizeConfig* p = config_;
  // @@protoc_insertion_point(field_get:techmo.tribune.SynthesizeRequest.config)
  return p != nullptr ? *p : *reinterpret_cast<const ::techmo::tribune::SynthesizeConfig*>(
      &::techmo::tribune::_SynthesizeConfig_default_instance_);
}
inline ::techmo::tribune::SynthesizeConfig* SynthesizeRequest::release_config() {
  // @@protoc_insertion_point(field_release:techmo.tribune.SynthesizeRequest.config)
  
  ::techmo::tribune::SynthesizeConfig* temp = config_;
  config_ = nullptr;
  return temp;
}
inline ::techmo::tribune::SynthesizeConfig* SynthesizeRequest::mutable_config() {
  
  if (config_ == nullptr) {
    auto* p = CreateMaybeMessage<::techmo::tribune::SynthesizeConfig>(GetArenaNoVirtual());
    config_ = p;
  }
  // @@protoc_insertion_point(field_mutable:techmo.tribune.SynthesizeRequest.config)
  return config_;
}
inline void SynthesizeRequest::set_allocated_config(::techmo::tribune::SynthesizeConfig* config) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete config_;
  }
  if (config) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      config = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, config, submessage_arena);
    }
    
  } else {
    
  }
  config_ = config;
  // @@protoc_insertion_point(field_set_allocated:techmo.tribune.SynthesizeRequest.config)
}

// -------------------------------------------------------------------

// SynthesizeConfig

// int32 sample_rate_hertz = 1;
inline void SynthesizeConfig::clear_sample_rate_hertz() {
  sample_rate_hertz_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 SynthesizeConfig::sample_rate_hertz() const {
  // @@protoc_insertion_point(field_get:techmo.tribune.SynthesizeConfig.sample_rate_hertz)
  return sample_rate_hertz_;
}
inline void SynthesizeConfig::set_sample_rate_hertz(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  sample_rate_hertz_ = value;
  // @@protoc_insertion_point(field_set:techmo.tribune.SynthesizeConfig.sample_rate_hertz)
}

// -------------------------------------------------------------------

// SynthesizeResponse

// .techmo.tribune.AudioData audio = 1;
inline bool SynthesizeResponse::has_audio() const {
  return this != internal_default_instance() && audio_ != nullptr;
}
inline void SynthesizeResponse::clear_audio() {
  if (GetArenaNoVirtual() == nullptr && audio_ != nullptr) {
    delete audio_;
  }
  audio_ = nullptr;
}
inline const ::techmo::tribune::AudioData& SynthesizeResponse::audio() const {
  const ::techmo::tribune::AudioData* p = audio_;
  // @@protoc_insertion_point(field_get:techmo.tribune.SynthesizeResponse.audio)
  return p != nullptr ? *p : *reinterpret_cast<const ::techmo::tribune::AudioData*>(
      &::techmo::tribune::_AudioData_default_instance_);
}
inline ::techmo::tribune::AudioData* SynthesizeResponse::release_audio() {
  // @@protoc_insertion_point(field_release:techmo.tribune.SynthesizeResponse.audio)
  
  ::techmo::tribune::AudioData* temp = audio_;
  audio_ = nullptr;
  return temp;
}
inline ::techmo::tribune::AudioData* SynthesizeResponse::mutable_audio() {
  
  if (audio_ == nullptr) {
    auto* p = CreateMaybeMessage<::techmo::tribune::AudioData>(GetArenaNoVirtual());
    audio_ = p;
  }
  // @@protoc_insertion_point(field_mutable:techmo.tribune.SynthesizeResponse.audio)
  return audio_;
}
inline void SynthesizeResponse::set_allocated_audio(::techmo::tribune::AudioData* audio) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete audio_;
  }
  if (audio) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      audio = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, audio, submessage_arena);
    }
    
  } else {
    
  }
  audio_ = audio;
  // @@protoc_insertion_point(field_set_allocated:techmo.tribune.SynthesizeResponse.audio)
}

// .techmo.tribune.Error error = 2;
inline bool SynthesizeResponse::has_error() const {
  return this != internal_default_instance() && error_ != nullptr;
}
inline void SynthesizeResponse::clear_error() {
  if (GetArenaNoVirtual() == nullptr && error_ != nullptr) {
    delete error_;
  }
  error_ = nullptr;
}
inline const ::techmo::tribune::Error& SynthesizeResponse::error() const {
  const ::techmo::tribune::Error* p = error_;
  // @@protoc_insertion_point(field_get:techmo.tribune.SynthesizeResponse.error)
  return p != nullptr ? *p : *reinterpret_cast<const ::techmo::tribune::Error*>(
      &::techmo::tribune::_Error_default_instance_);
}
inline ::techmo::tribune::Error* SynthesizeResponse::release_error() {
  // @@protoc_insertion_point(field_release:techmo.tribune.SynthesizeResponse.error)
  
  ::techmo::tribune::Error* temp = error_;
  error_ = nullptr;
  return temp;
}
inline ::techmo::tribune::Error* SynthesizeResponse::mutable_error() {
  
  if (error_ == nullptr) {
    auto* p = CreateMaybeMessage<::techmo::tribune::Error>(GetArenaNoVirtual());
    error_ = p;
  }
  // @@protoc_insertion_point(field_mutable:techmo.tribune.SynthesizeResponse.error)
  return error_;
}
inline void SynthesizeResponse::set_allocated_error(::techmo::tribune::Error* error) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete error_;
  }
  if (error) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      error = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, error, submessage_arena);
    }
    
  } else {
    
  }
  error_ = error;
  // @@protoc_insertion_point(field_set_allocated:techmo.tribune.SynthesizeResponse.error)
}

// -------------------------------------------------------------------

// AudioData

// int32 sample_rate_hertz = 1;
inline void AudioData::clear_sample_rate_hertz() {
  sample_rate_hertz_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 AudioData::sample_rate_hertz() const {
  // @@protoc_insertion_point(field_get:techmo.tribune.AudioData.sample_rate_hertz)
  return sample_rate_hertz_;
}
inline void AudioData::set_sample_rate_hertz(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  sample_rate_hertz_ = value;
  // @@protoc_insertion_point(field_set:techmo.tribune.AudioData.sample_rate_hertz)
}

// bytes content = 2;
inline void AudioData::clear_content() {
  content_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& AudioData::content() const {
  // @@protoc_insertion_point(field_get:techmo.tribune.AudioData.content)
  return content_.GetNoArena();
}
inline void AudioData::set_content(const std::string& value) {
  
  content_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:techmo.tribune.AudioData.content)
}
inline void AudioData::set_content(std::string&& value) {
  
  content_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:techmo.tribune.AudioData.content)
}
inline void AudioData::set_content(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  content_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:techmo.tribune.AudioData.content)
}
inline void AudioData::set_content(const void* value, size_t size) {
  
  content_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:techmo.tribune.AudioData.content)
}
inline std::string* AudioData::mutable_content() {
  
  // @@protoc_insertion_point(field_mutable:techmo.tribune.AudioData.content)
  return content_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* AudioData::release_content() {
  // @@protoc_insertion_point(field_release:techmo.tribune.AudioData.content)
  
  return content_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void AudioData::set_allocated_content(std::string* content) {
  if (content != nullptr) {
    
  } else {
    
  }
  content_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), content);
  // @@protoc_insertion_point(field_set_allocated:techmo.tribune.AudioData.content)
}

// bool end_of_stream = 3;
inline void AudioData::clear_end_of_stream() {
  end_of_stream_ = false;
}
inline bool AudioData::end_of_stream() const {
  // @@protoc_insertion_point(field_get:techmo.tribune.AudioData.end_of_stream)
  return end_of_stream_;
}
inline void AudioData::set_end_of_stream(bool value) {
  
  end_of_stream_ = value;
  // @@protoc_insertion_point(field_set:techmo.tribune.AudioData.end_of_stream)
}

// -------------------------------------------------------------------

// Error

// .techmo.tribune.ErrorCode code = 1;
inline void Error::clear_code() {
  code_ = 0;
}
inline ::techmo::tribune::ErrorCode Error::code() const {
  // @@protoc_insertion_point(field_get:techmo.tribune.Error.code)
  return static_cast< ::techmo::tribune::ErrorCode >(code_);
}
inline void Error::set_code(::techmo::tribune::ErrorCode value) {
  
  code_ = value;
  // @@protoc_insertion_point(field_set:techmo.tribune.Error.code)
}

// string description = 2;
inline void Error::clear_description() {
  description_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& Error::description() const {
  // @@protoc_insertion_point(field_get:techmo.tribune.Error.description)
  return description_.GetNoArena();
}
inline void Error::set_description(const std::string& value) {
  
  description_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:techmo.tribune.Error.description)
}
inline void Error::set_description(std::string&& value) {
  
  description_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:techmo.tribune.Error.description)
}
inline void Error::set_description(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  description_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:techmo.tribune.Error.description)
}
inline void Error::set_description(const char* value, size_t size) {
  
  description_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:techmo.tribune.Error.description)
}
inline std::string* Error::mutable_description() {
  
  // @@protoc_insertion_point(field_mutable:techmo.tribune.Error.description)
  return description_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* Error::release_description() {
  // @@protoc_insertion_point(field_release:techmo.tribune.Error.description)
  
  return description_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void Error::set_allocated_description(std::string* description) {
  if (description != nullptr) {
    
  } else {
    
  }
  description_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), description);
  // @@protoc_insertion_point(field_set_allocated:techmo.tribune.Error.description)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace tribune
}  // namespace techmo

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::techmo::tribune::ErrorCode> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::techmo::tribune::ErrorCode>() {
  return ::techmo::tribune::ErrorCode_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_tribune_5ftts_2eproto
